//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public System.Guid EmpID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public string Martial_Status { get; set; }
        public byte[] Matric { get; set; }
        public byte[] Intermediate { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Status { get; set; }
        public string CNIC { get; set; }
        public byte[] Picture { get; set; }
        public string Religion { get; set; }
    }
}
