//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Overall_Fees
    {
        public Overall_Fees()
        {
            this.Fees = new HashSet<Fee>();
        }
    
        public string RollNo { get; set; }
        public Nullable<decimal> Total_Degree_Fee { get; set; }
        public Nullable<decimal> SubmittedFee { get; set; }
        public Nullable<decimal> RemainingFee { get; set; }
        public Nullable<int> Total_Installments { get; set; }
        public Nullable<int> Paid_Installments { get; set; }
    
        public virtual ICollection<Fee> Fees { get; set; }
        public virtual Registeration Registeration { get; set; }
    }
}
