//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public Part()
        {
            this.Batch_Subjects_Parts = new HashSet<Batch_Subjects_Parts>();
            this.Degree_Subject = new HashSet<Degree_Subject>();
            this.Registerations = new HashSet<Registeration>();
        }
    
        public int PartID { get; set; }
        public Nullable<int> Part1 { get; set; }
    
        public virtual ICollection<Batch_Subjects_Parts> Batch_Subjects_Parts { get; set; }
        public virtual ICollection<Degree_Subject> Degree_Subject { get; set; }
        public virtual ICollection<Registeration> Registerations { get; set; }
    }
}
