//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_6
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptOverallFee
    {
        public string RollNo { get; set; }
        public decimal Total_Degree_Fee { get; set; }
        public decimal SubmittedFee { get; set; }
        public decimal RemainingFee { get; set; }
        public int Total_Installments { get; set; }
        public int Paid_Installments { get; set; }
    }
}
