//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_6
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptStudentMark
    {
        public string RollNo { get; set; }
        public string Name { get; set; }
        public string SubjectName { get; set; }
        public int TotalMarks { get; set; }
        public double ObtainedMarks { get; set; }
        public string Marks_Percentage { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string BatchName { get; set; }
        public string SectionName { get; set; }
        public string Degree_Programme { get; set; }
        public string Part { get; set; }
    }
}
