//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_6
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPTStudentFee
    {
        public string Bill_No { get; set; }
        public string Rollno { get; set; }
        public string StudentName { get; set; }
        public System.DateTime Dated { get; set; }
        public decimal Registeration_Fee { get; set; }
        public decimal Tution_Fee { get; set; }
        public decimal Admission_Fee { get; set; }
        public decimal Exam_Fee { get; set; }
        public int Total_Installments { get; set; }
        public int Installment { get; set; }
        public string Month { get; set; }
        public decimal Fine { get; set; }
        public decimal Total_Fee { get; set; }
    }
}
