//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_6
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptTotalstudentForEmploy
    {
        public string Rollno { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Degree_ProgramName { get; set; }
        public int Part { get; set; }
        public string Duration { get; set; }
        public string Section { get; set; }
    }
}
