//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.Batches = new HashSet<Batch>();
        }
    
        public System.Guid SectionID { get; set; }
        public string SectionName { get; set; }
    
        public virtual ICollection<Batch> Batches { get; set; }
    }
}
