//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Batch_Subjects_Parts = new HashSet<Batch_Subjects_Parts>();
            this.Degree_Subject = new HashSet<Degree_Subject>();
            this.Teacher_Subject = new HashSet<Teacher_Subject>();
        }
    
        public System.Guid SubjectID { get; set; }
        public string SubjectName { get; set; }
    
        public virtual ICollection<Batch_Subjects_Parts> Batch_Subjects_Parts { get; set; }
        public virtual ICollection<Degree_Subject> Degree_Subject { get; set; }
        public virtual ICollection<Teacher_Subject> Teacher_Subject { get; set; }
    }
}
