//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Year
    {
        public Year()
        {
            this.Batches = new HashSet<Batch>();
        }
    
        public System.Guid YearID { get; set; }
        public Nullable<int> FromYear { get; set; }
        public Nullable<int> ToYear { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<Batch> Batches { get; set; }
    }
}
