//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_6
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardResult
    {
        public System.Guid ID { get; set; }
        public string Rollno { get; set; }
        public byte[] FirstYearMarkSheet { get; set; }
        public byte[] SecondYearMarkSheet { get; set; }
        public byte[] ThirdYearMarkSheet { get; set; }
        public byte[] FourthYearMarkSheet { get; set; }
    }
}
