//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degree_Subject
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> DegreeID { get; set; }
        public Nullable<System.Guid> SubjectID { get; set; }
        public Nullable<int> Part { get; set; }
    
        public virtual Degree_Program Degree_Program { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Part Part1 { get; set; }
    }
}
