//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public string Bill_No { get; set; }
        public string Rollno { get; set; }
        public string StudentName { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public Nullable<decimal> Registeration_Fee { get; set; }
        public Nullable<decimal> Tution_Fee { get; set; }
        public Nullable<decimal> Admission_Fee { get; set; }
        public Nullable<decimal> Exam_Fee { get; set; }
        public Nullable<int> Total_Installments { get; set; }
        public Nullable<int> Installment { get; set; }
        public string Month { get; set; }
        public Nullable<decimal> Fine { get; set; }
        public Nullable<decimal> Total_Fee { get; set; }
    
        public virtual Registeration Registeration { get; set; }
    }
}
