//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Profile
    {
        public Student_Profile()
        {
            this.Registerations = new HashSet<Registeration>();
        }
    
        public System.Guid ProfileID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public string CNIC { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public Nullable<int> Matric_Marks { get; set; }
        public Nullable<int> Intermediate_Marks { get; set; }
        public string Domicile { get; set; }
        public string Nationality { get; set; }
        public byte[] Picture { get; set; }
        public string FatherName_Guardian_Name { get; set; }
        public string Father_Guardian_Contact { get; set; }
        public string Father_Guardian_Occupation { get; set; }
        public string MatricFrom { get; set; }
        public string IntermediateFrom { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<Registeration> Registerations { get; set; }
    }
}
