//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Teacher_Attendance = new HashSet<Teacher_Attendance>();
            this.Teachers_Batches = new HashSet<Teachers_Batches>();
        }
    
        public string TeacherID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public string Martial_Status { get; set; }
        public string Graduation_Details { get; set; }
        public string Post_Graduation_Details { get; set; }
        public Nullable<int> Year_of_Graduation { get; set; }
        public Nullable<int> Year_of_Post_Graduation { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Status { get; set; }
        public string Major_Subject { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual ICollection<Teacher_Attendance> Teacher_Attendance { get; set; }
        public virtual ICollection<Teachers_Batches> Teachers_Batches { get; set; }
    }
}
